import type { Metadata } from "next";
import "./globals.css";
import {Poppins} from "next/font/google"

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "MicroSaas Boiler plate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} bg-gray-100 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
